version: '3.8'

services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jmeter-master
    hostname: master
    environment:
      - JMETER_VERSION=${JMETER_VERSION}
      - JMETER_DIR=/opt/apache-jmeter-${JMETER_VERSION}
      - TEST_PLAN_PATH=${TEST_PLAN_PATH}
      - RESULT_PATH=${RESULT_PATH}
      - INFLUXDB_URL=http://influxdb:8086/api/v2/write
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - APPLICATION_NAME=${APPLICATION_NAME}
    volumes:
      - ./test-files:/test-files
    networks:
      jmeter-net:
        ipv4_address: 172.28.100.10
    ports:
      - "2222:22"

  slave1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jmeter-slave1
    hostname: slave1
    environment:
      - JMETER_VERSION=${JMETER_VERSION}
      - JMETER_DIR=/opt/apache-jmeter-${JMETER_VERSION}
    volumes:
      - ./test-files:/test-files
    networks:
      jmeter-net:
        ipv4_address: 172.28.100.11
    ports:
      - "2223:22"

  slave2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jmeter-slave2
    hostname: slave2
    environment:
      - JMETER_VERSION=${JMETER_VERSION}
      - JMETER_DIR=/opt/apache-jmeter-${JMETER_VERSION}
    volumes:
      - ./test-files:/test-files
    networks:
      jmeter-net:
        ipv4_address: 172.28.100.12
    ports:
      - "2224:22"

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    networks:
      jmeter-net:

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-pyroscope-app,grafana-exploretraces-app
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      jmeter-net:

networks:
  jmeter-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.100.0/24

volumes:
  influxdb-storage:
